[config]
[templates.kitty]
input_path = "~/.config/noctalia/user-templates/kitty/theme-template.conf"
output_path = "~/.config/noctalia/user-templates/kitty/theme.conf"
post_hook = "pkill -SIGUSR1 kitty"
